service: default
runtime: python39

basic_scaling:
    max_instances: 2
    idle_timeout: 10m

resources:
    cpu: 1
    memory_gb: 1
    disk_size_gb: 1

env_variables:
PORT: 8080

entrypoint: gunicorn -b :$PORT main:server